# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "AI2001_Category-Source_Code-SC-Swift_Main-dev" ]
  pull_request:
    branches: [ "AI2001_Category-Source_Code-SC-Swift_Main-dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
